config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  get 'pages/home'
  root 'pages#home'
  resources :recipes do
    resources :steps, except: [:index, :show, :edit] do
      put 'up', to: 'steps#up', as: :up
      put 'down', to: 'steps#down', as: :down
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id    :integer          not null, primary key
#  name  :string
#  image :string
#

class Recipe < ApplicationRecord
  validates :name, presence: true, length: { maximum: 300 }
  validates :image, presence: true

  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :steps, dependent: :destroy

  accepts_nested_attributes_for :recipe_ingredients

  def quantity(ingredient)
    if ingredients.include?(ingredient)
      return recipe_ingredients.where(ingredient_id: ingredient.id).first.quantity
    else
      return 0
    end
  end

  def energy
    energy = 0
    recipe_ingredients.each do |ri|
      energy += ri.ingredient.energy / 100 * ri.quantity
    end
    return energy
  end

  def proteins
    proteins = 0
    recipe_ingredients.each do |ri|
      proteins += ri.ingredient.proteins / 100 * ri.quantity
    end
    return proteins
  end

  def carbohydrates
    carbohydrates = 0
    recipe_ingredients.each do |ri|
      carbohydrates += ri.ingredient.carbohydrates / 100 * ri.quantity
    end
    return carbohydrates
  end

  def fat
    fat = 0
    recipe_ingredients.each do |ri|
      fat += ri.ingredient.fat / 100 * ri.quantity
    end
    return fat
  end

  def cook_time
    ct = 0
    steps.each do |step|
      ct += step.seconds
    end
    return ct
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
    if @recipes.empty?
      add_flash_messages("error", ["There are no recipes yet"], false )
    end
  end

  def new
    if Ingredient.count == 0
      redirect_to new_ingredient_path
    else
      @recipe = Recipe.new
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    ingredients_hash = ingredients_params
    unless ingredients_hash.blank?
      update_ingredients ingredients_params
      if @recipe.recipe_ingredients.empty?
        add_flash_messages("error", ["Ingredients can't be blank"], false)
        render :new
      elsif @recipe.save
        redirect_to new_recipe_step_path(@recipe.id)
      else
        add_flash_messages("error", @recipe.errors.full_messages, false)
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    Recipe.transaction do
      update_ingredients ingredients_params
      if @recipe.update(recipe_params)
        redirect_to recipes_path
      else
        add_flash_messages("error", @recipe.errors.full_messages, false)
        render :edit
      end
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def update_ingredients(ingredients_hash)
    ingredients_hash.each do |id, quantity|
      if quantity.to_f == 0
        @recipe.recipe_ingredients.where(ingredient_id: id).first.try(:destroy)
      elsif @recipe.ingredients.pluck(:id).include?(id)
        @recipe.recipe_ingredients.where(ingredient_id: id).first.update(quantity: quantity)
      else
        @recipe.recipe_ingredients.build(ingredient_id: id, quantity: quantity)
      end
    end
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    add_flash_messages("error", ["This recipe does not exist"], true)
    redirect_to recipes_path
  end

  def recipe_params
    params.require(:recipe).permit(:name, :image)
  end

  def ingredients_params
    params.require("ingredients").permit!
  rescue ActionController::ParameterMissing
    add_flash_messages("error", ["Ingredients can't be blank"], false)
    render :new
  end
end

app/views/recipes/_edit_steps.html.haml
%h2 Steps
.list-group
  - @recipe.steps.order(:order).each do |step|
    .list-group-item
      .row
        .col-12.d-md-none.d-l-none.d-xl-none
          %h3="Step #{step.order}"
        .col-md-1.d-none.d-md-block.d-l-block.d-xl-block
          .btn.btn-primary
            = step.order
        .col-12.col-md-11
          = form_for [@recipe, step] do |f|
            .form-group
              = f.label :image
              = f.text_field :image, id: "step_#{step.order}_image", class: "form-control"
            .form-group
              = f.label :description
              = f.text_area :description, id: "step_#{step.order}_description", class: "form-control"
            .form-group
              = f.label :seconds
              = f.number_field :seconds, id: "step_#{step.order}_seconds", class: "form-control"
            .form-group
              = f.submit 'Save', class: "btn btn-primary"
              = link_to "Delete", recipe_step_path(@recipe, step), method: "delete", class: "btn btn-danger", data: {confirm: 'Are you sure?'}
              - if step.order!=1
                = link_to 'Up', recipe_step_up_path(@recipe, step), method: 'put', class: "btn btn-warning"
              - if step.order!=@recipe.steps.count
                = link_to 'Down', recipe_step_down_path(@recipe, step), method: 'put', class: "btn btn-warning"
= button_to "New step", new_recipe_step_path(@recipe), method: "get", class: "btn btn-success"

app/views/recipes/_form.html.haml
= form_for @recipe do |f|
  .form-group.row
    = f.label :name, class: "col-12 col-md-2"
    = f.text_field :name, class: "form-control col-12 col-md-10"
  .form-group.row
    = f.label :image, class: "col-12 col-md-2"
    = f.text_field :image, class: "form-control col-12 col-md-10"
  .form-group
    %h2 Ingredients
    .alert.alert-primary
      Select some ingredients by filling the quantity in grams

    .list-group.scrollable
      - Ingredient.all.each do |ingredient|
        .list-group-item
          .row
            .col-6.col-md-8
              = label_tag ingredient.name
            .col-6.col-md-4
              .row
                .col-9
                  = text_field_tag "ingredients[#{ingredient.id}]", @recipe.quantity(ingredient), id: "#{ingredient.name}_quantity", class: "form-control"
                .col-2 g
            %br

  = f.submit @recipe.persisted? ? "Save" : "Create steps", class: "btn btn-primary"

app/views/recipes/_recipe.html.haml
.card
  %img.card-img-top{:alt => "#{recipe.name}", :src => "#{recipe.image}"}/
  .card-body
    %h5.card-text=recipe.name
  .card-footer
    .row
      = button_to "Cook", recipe, method: "get", class: "btn btn-primary"
      = button_to "Edit", edit_recipe_path(recipe), method: "get", class: "btn btn-success"
      = button_to "Delete", recipe, method: "delete", class: "btn btn-danger", data: { confirm: "Are your sure?"}

app/views/recipes/edit.html.haml
%h1 Edit recipe
.row
  .col-12.col-md-6
    = render 'form'
  .col-12.col-md-6
    = render 'edit_steps'

app/views/recipes/index.html.haml
.card-columns.bottom-bar-container
  = render @recipes
%nav.navbar.fixed-bottom.navbar-light.bg-light
  = button_to "New recipe", new_recipe_path, method: "get", class: "btn btn-success"

app/views/recipes/new.html.haml
.row
  .col-12.col-md-6.offset-md-3
    %h1 New recipe
    = render 'form'

app/views/recipes/show.html.haml
.row
  .col-11.offset-1
    %h1.text-center=@recipe.name
    .text-center.text-muted.mb-4="Time: #{@recipe.cook_time} seconds"
  .col-md-4.offset-md-1
    = image_tag @recipe.image, class: "img-fluid"
    .card
      .card-header Nutritional info
      .card-body
        %table.table
          %tbody
            %tr
              %th{scope: "row"} Energy
              %td=((@recipe.energy*100).round/100.0).to_s + " kcal"
            %tr
              %th{scope: "row"} Fat
              %td=((@recipe.fat*100).round/100.0).to_s + " g"
            %tr
              %th{scope: "row"} Proteins
              %td=((@recipe.proteins*100).round/100.0).to_s + " g"
            %tr
              %th{scope: "row"} Carbohydrates
              %td=((@recipe.carbohydrates*100).round/100.0).to_s + " g"
    .card
      .card-header Ingredients
      .card-body
        %ul
          - @recipe.recipe_ingredients.each do |ri|
            %li="#{ri.quantity}g #{ri.ingredient.name}"

  .col-md-6
    %h2.my-4 Steps
    - if @recipe.steps.empty?
      .alert.alert-danger
        This recipe has no steps
    - else
      .list-group
        - @recipe.steps.order(:order).each do |step|
          .list-group-item
            .row
              .col-md-1.d-none.d-md-block
                .btn.btn-primary
                  = step.order
              .col-12.col-md-3
                = image_tag step.image, class: "img-fluid"
              .col-12.col-md-8
                .row
                  .col-12
                    .text-muted="Time: #{step.seconds}s"
                  .col-12
                    = step.description