config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  get 'pages/home'
  root 'pages#home'
  resources :recipes do
    resources :steps, except: [:index, :show, :edit] do
      put 'up', to: 'steps#up', as: :up
      put 'down', to: 'steps#down', as: :down
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id            :integer          not null, primary key
#  name          :string
#  energy        :float
#  fat           :float
#  proteins      :float
#  carbohydrates :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { maximum: 200 }
  validates :energy, numericality: { greater_than_or_equal_to: 0, message: "Energy can't be negative" }

  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
    if @ingredients.empty?
      add_flash_messages("error", ["There are no ingredients yet"], false )
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      add_flash_messages("success", ["Ingredient succesfully created"], true )
      redirect_to @ingredient
    else
      add_flash_messages("error", @ingredient.errors.full_messages, true)
      render :new
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    if @ingredient.update(ingredient_params)
      add_flash_messages("success", ["Ingredient succesfully updated"], true )
      redirect_to @ingredient
    else
      add_flash_messages("error", @ingredient.errors.full_messages, true)
      render :edit
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy

    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      add_flash_messages("error", ["This ingredient does not exist"], true)
      redirect_to ingredients_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :energy, :fat, :proteins, :carbohydrates)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :energy
    = f.text_field :energy, class: "form-control"
  .form-group
    = f.label :fat
    = f.text_field :fat, class: "form-control"
  .form-group
    = f.label :proteins
    = f.text_field :proteins, class: "form-control"
  .form-group
    = f.label :carbohydrates
    = f.text_field :carbohydrates, class: "form-control"
  .form-group.row
    = f.submit 'Save', class: "btn btn-success"
    = link_to 'Back', ingredients_path, class: "btn btn-danger"

app/views/ingredients/edit.html.haml
.row
  .col-md-4.offset-md-4

    %h1 Editing ingredient

    = render 'form'

app/views/ingredients/index.html.haml
.row.bottom-bar-container
  .col-md-4.offset-md-4
    %h1 Ingredients
    %ul.list-group
      - @ingredients.each do |ingredient|
        %li.list-group-item.d-flex.justify-content-between.align-items-center
          = link_to ingredient.name, ingredient
          .row
            = link_to "Edit", edit_ingredient_path(ingredient), class: "btn btn-primary"
            = link_to "Delete", ingredient, method: "delete", class: "btn btn-danger", data: { confirm: "Are your sure?"}
%nav.navbar.fixed-bottom.navbar-light.bg-light
  = button_to "New ingredient", new_ingredient_path, method: "get", class: "btn btn-success"

app/views/ingredients/new.html.haml
.row
  .col-md-4.offset-md-4
    %h1 New ingredient

    = render 'form'

app/views/ingredients/show.html.haml
.row
  .col-md-4.offset-md-4
    %h1= @ingredient.name

    %h2 Values per 100g

    %table.table
      %tbody
        %tr
          %th{scope: "row"} Energy (kcal)
          %td=@ingredient.energy
        %tr
          %th{scope: "row"} Fat (g)
          %td=@ingredient.fat
        %tr
          %th{scope: "row"} Proteins (g)
          %td=@ingredient.proteins
        %tr
          %th{scope: "row"} Carbohydrates (g)
          %td=@ingredient.carbohydrates


    = link_to 'Edit', edit_ingredient_path(@ingredient), class: "btn btn-primary"
    = link_to 'Back', ingredients_path, class: "btn btn-danger"