config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  get 'pages/home'
  root 'pages#home'
  resources :recipes do
    resources :steps, except: [:index, :show, :edit] do
      put 'up', to: 'steps#up', as: :up
      put 'down', to: 'steps#down', as: :down
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.haml
- flash.each do |type, messages|
  %div{class: "#{flash_class(type)} alert-dismissible fade show", role: "alert"}
    - messages.each do |message|
      %p=message
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand.navbar-light.bg-light
  = link_to "Recigram", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item
        = link_to "Recipes", recipes_path, class: "nav-link #{active_class(recipes_path)} "
      %li.nav-item
        = link_to "Ingredients", ingredients_path, class: "nav-link #{active_class(ingredients_path)}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title Recigram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/errors'
    .container-fluid
      = yield